name: Publish Docker Image

on:
  push:
    tags:
      - 'v*'  # Esto activará el flujo de trabajo al crear un tag que comience con "v"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/mi-imagen"
        TAG="${GITHUB_REF##*/}"  # Obtiene el tag del contexto de GitHub
        docker build -t $IMAGE_NAME:$TAG .

    - name: Push the Docker image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/mi-imagen"
        TAG="${GITHUB_REF##*/}"
        docker push $IMAGE_NAME:$TAG
